---
- name: Create a network
  docker_network:
    name: waf-center

- name: Run Consul container        
  docker_container:
    name: consul
    networks: 
        - name: waf-center
    image: progrium/consul 
    restart_policy: always
    state: started
    command: -server -bootstrap -ui-dir /ui
    ports:
        - 8400:8400
        - 8500:8500
        - 8600:53/udp 
           

