---
- name: Pull Consul image
  docker_image:
        name: consul
        tag: latest

- name: Run Consul container        
  docker_container:
    name: consul-docker-ct
    image: consul  
    restart_policy: always
    state: started
    command: agent -ui -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1 
    ports:
        - 8500:8500
        - 8600:8600/udp 
           

